# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils
# Install some other useful utilities like `sponge`
install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
install findutils
# Install Zsh
install zsh

# Install Gitignore Boilerplate (gibo)
install gibo

# Install wget with IRI support
install wget --enable-iri

# Install more recent versions of some OS X tools
install vim --override-system-vi
#install homebrew/dupes/grep
tap homebrew/dupes
install grep
#install josegonzalez/homebrew-php/php55
tap josegonzalez/homebrew-php
install --without-apache --with-fpm --with-mysql php55
install mysql
install nginx

# Install other useful binaries
install git
install hub

# Remove outdated versions from the cellar
cleanup
